<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>安居综合保险条款C</title>
<%@include file="../../common/head.jsp"%>
</head>
<body onload="loaded();">
		<div id="baoqiandai_content" style="width: 100%;">
			<!-- <div data-role="header" data-position="fixed" class="zll_header" data-tap-toggle="false">
				onclick="$.mobile.changePage('../../index.html', 'slideup');"
			    <a data-ajax="false" href="javascript:history.go(-1);" class="ui-btn ui-corner-all ui-btn-icon-notext ui-icon-back">返回</a>
			    <h2>安居综合保险条款C</h2>
			</div> -->
            <header>
                <div class="header-left" onclick="history.go(-1);">
                  <div class="header-btn-area">
                      <!-- <i class="iconfont icon-fanhuijiantou"></i> --> 
                      <%-- <img src="${staticPath }/img/icon/left.png" width="15px" alt="" height="15px"/> --%>
                      <!-- <span class="left-btn"></span> -->
                      <span class="icon_img back"></span>
                  </div>
                </div>
                <div class="header-tit"><h2>安居综合保险条款C</h2></div>
                <div class="header-right">
                  
                </div>
           </header>
			<!--内容页-->
			<div id="wrapper" >
              <div id="scroller">
              <main  class="ui-content insurance_detail">
				<h3 align="center" style="margin-top:5.25pt;margin-right:0cm;margin-bottom:5.25pt;margin-left:0cm;text-align:center"><span style="font-family:'color:#333333;font-weight:normal';font-size:10px">总 则</span><span style="font-size:11.5pt;font-family:&quot;color:#333333;font-weight:normal"></span></h3><p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第一条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">本保险合同（以下简称为“本合同”）由投保单、保险单或其他保险凭证及所附条款，与本合同有关的投保文件、声明、批注、附贴批单及其他书面文件构成。凡涉及本合同的约定，均应采用书面形式。</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<h3><span style="font-family:微软雅黑, sans-serif;font-weight:normal;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">保险标的</span><span style="font-family:微软雅黑, sans-serif;font-weight:normal"></span></h3><p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第二条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">保险单中载明的下列财产为本合同保险标的：</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p align="left"><span style="font-family:微软雅黑, sans-serif"><span style="font-size:10px">（一）用于居住的房屋及房屋内装潢；</span><span><br/>
</span><span style="font-size:10px">（二）房屋内的家具、除手提电话和便携式电脑以外的家用电器、床上用品、服装。</span></span><span></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第三条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">上述未列明的其他财产，不在本合同保险标的范围内。</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<h3><span style="font-family:微软雅黑, sans-serif;font-weight:normal;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">保险责任</span><span style="font-family:微软雅黑, sans-serif;font-weight:normal"></span></h3><p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第四条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">家庭财产保险</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p align="left"><span style="font-family:微软雅黑, sans-serif"><span style="font-size:10px">（一）在保险期间内，由于下列原因造成保险标的的损失，保险人按照本合同的约定负责赔偿：</span><span><br/>
<span style="font-size:10px">1</span></span><span style="font-size:10px">、火灾、爆炸、水管爆裂；</span><span><br/>
<span style="font-size:10px">2</span></span><span style="font-size:10px">、雷击、台风、暴风、暴雨、龙卷风、洪水、雪灾、雹灾、冰凌、地面突然塌陷；</span><span><br/>
<span style="font-size:10px">3</span></span><span style="font-size:10px">、飞行物体及其他空中运行物体坠落；</span><span><br/>
<span style="font-size:10px">4</span></span><span style="font-size:10px">、不属于被保险人所有或使用的建筑或其他固定物体发生倒塌；</span><span><br/>
<span style="font-size:10px">5</span></span><span style="font-size:10px">、有明显撬窃痕迹的盗窃；</span><span><br/>
<span style="font-size:10px">6</span></span><span style="font-size:10px">、入室抢劫。</span><span><br/>
</span><span style="font-size:10px">（二）由于保险标的发生保险事故而导致被保险人无法居住，需临时租借房屋所发生的租借费用，保险人也负责赔偿。</span><span><br/>
</span><span style="font-size:10px">租借费用最高赔偿限额为家庭财产保险金额的</span><span style="font-size:10px">10%</span><span style="font-size:10px">。家庭财产保险每投保</span><span style="font-size:10px">1</span><span style="font-size:10px">万元</span><span style="font-size:10px">,</span><span style="font-size:10px">租借费用每天赔偿限额为</span><span style="font-size:10px">100</span><span style="font-size:10px">元人民币；如果家庭财产保险投保</span><span style="font-size:10px">3</span><span style="font-size:10px">万元（含）以上的，租借费用每天赔偿限额为</span><span style="font-size:10px">300</span><span style="font-size:10px">元人民币。租借费用与家庭财产部分的赔偿总额不超过家庭财产保险的总保险金额。</span><span><br/>
</span><span style="font-size:10px">（三）保险事故发生后，被保险人为防止或者减少保险标的的损失所支付的必要、合理的费用（以下简称为“施救费用”），保险人按照本合同的约定也负责赔偿。</span></span><span></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第五条</span></strong><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">对第三者的经济赔偿责任</span><span><br/>
</span><span style="font-size:10px">（一）在保险期间内，被保险人房屋附属的安装物、搁置物、悬挂物、管道，因意外事故造成倒塌、脱落、坠落、爆裂致使第三者人身伤亡或财产损失，依照中华人民共和国法律（不包括港澳台地区法律，下同）应由被保险人或其家庭成员承担经济赔偿责任的，保险人按照本合同的约定负责赔偿。</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">（二）保险事故发生后，被保险人因保险事故而被提起仲裁或者诉讼的，对应由被保险人支付的仲裁或诉讼费用以及事先经保险人书面同意支付的其他必要的、合理的费用（以下简称为“法律费用”），保险人按照本合同的约定负责赔偿。</span><span style="font-size:10px">&nbsp;</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<h3><span style="font-family:微软雅黑, sans-serif;font-weight:normal;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">责任免除</span><span style="font-family:微软雅黑, sans-serif;font-weight:normal"></span></h3><p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第六条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">下列原因造成的保险标的损失，保险人不负责赔偿：</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p align="left"><span style="font-family:微软雅黑, sans-serif"><span style="font-size:10px">（一）设计错误、勘察错误、原材料缺陷、工艺不善、施工质量问题；</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">（二）保险标的自然磨损、内在或潜在缺陷、自然损耗，大气（气候或气温）变化、正常水位变化或其他渐变原因、物质本身变化、自燃、自热、霉烂、受潮、鼠咬、虫蛀、鸟啄、氧化、锈蚀、渗漏、烘焙；</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">（三）家用电器使用不当、超电压、超负荷、短路、电弧花、漏电、自身发热或本身内在缺陷造成其本身的损毁；</span><span style="font-size:10px">&nbsp;</span></span><span></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第七条</span></strong><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">下列原因造成第三者的人身伤亡或财产损失，保险人不负责赔偿：</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">（一）被保险人或其家庭成员直接对第三者进行的身体伤害和财产损毁；</span><span><br/>
</span><span style="font-size:10px">（二）被保险人或其家庭成员的精神失常。</span><span style="font-size:10px">&nbsp;</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第八条</span></strong><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">下列原因造成的保险标的损失或对第三者的经济赔偿责任，保险人均不负责赔偿：</span><span><br/>
</span><span style="font-size:10px">（一）战争、敌对行为、军事行动、武装冲突、恐怖主义活动、罢工、暴动、骚乱；</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">（二）行政行为、司法行为；</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">（三）被保险人或其家庭成员的故意或重大过失行为；</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">（四）核爆炸、核裂变、核聚变；</span><span><br/>
</span><span style="font-size:10px">（五）放射性污染和其他各种环境污染；</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">（六）除第四条列明以外的其他自然灾害和意外事故；</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">（七）由于地震、海啸引起的地面突然塌陷。</span><span style="font-size:10px">&nbsp;</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第九条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">下列损失、费用和责任，保险人不负责赔偿：</span><span><br/>
</span><span style="font-size:10px">（一）间接损失；</span><span><br/>
</span><span style="font-size:10px">（二）违章搭建的建筑或设施装置、危险建筑以及非法占有、持有的财产的损失；</span><span><br/>
</span><span style="font-size:10px">（三）罚款、罚金或惩罚性赔款；</span><span><br/>
</span><span style="font-size:10px">（四）在合同或协议中约定的应由被保险人承担的赔偿责任，但即使没有这种合同或协议，被保险人依法仍应承担的赔偿责任不在本款责任免除范围内；</span><span><br/>
</span><span style="font-size:10px">（五）保险单中载明的应由被保险人自行承担的免赔额。</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第十条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">其他不属于本合同责任范围内的损失、费用和责任，保险人不负责赔偿。</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<h3><span style="font-family:微软雅黑, sans-serif;font-weight:normal;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">保险金额、赔偿限额和保险期间</span><span style="font-family:微软雅黑, sans-serif;font-weight:normal"></span></h3><p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第十一条</span></strong><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">本保险为定额保险，每份最高赔偿限额为人民币</span><span style="font-size:10px">1</span><span style="font-size:10px">万元。</span><span><br/>
</span><span style="font-size:10px">其中，家庭财产保险金额为保险单中载明的最高赔偿限额的</span><span style="font-size:10px">70%</span><span style="font-size:10px">；对第三者的经济赔偿责任的赔偿限额为保险单中载明的最高赔偿限额的</span><span style="font-size:10px">30%</span><span style="font-size:10px">。</span><span><br/>
</span><span style="font-size:10px">每户家庭可以同时拥有多份上述保险单，其分项保险金额或赔偿限额可以累计计算，赔偿金额以累计保险金额或赔偿限额为限。</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第十二条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">除另有约定外，保险期间为一年，以保险单中载明的起讫时间为准。</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第十三条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">本合同成立后，保险人应当及时向投保人签发保险单或其他保险凭证。</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第十四条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">保险人按照第二十五条的约定，认为被保险人所提供的有关索赔的证明和资料不完整的，应当及时一次性通知投保人、被保险人补充提供。</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第十五条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">保险人收到被保险人的赔偿保险金的请求后，应当及时对是否属于保险责任作出核定；情形复杂的，应当在三十日内作出核定；情形特别复杂的，由于非保险人可以控制的原因导致核定困难的，保险人应与被保险人商议合理核定期间，并在商定的期间内作出核定。</span><span><br/>
</span><span style="font-size:10px">保险人应当将核定结果通知被保险人；对属于保险责任的，在与被保险人达成赔偿保险金的协议后十日内，履行赔偿保险金义务。本合同对赔偿保险金的期限有约定的，保险人应当按照约定履行赔偿保险金的义务。保险人依照前款约定作出核定后，对不属于保险责任的，应当自作出核定之日起三日内向被保险人发出拒绝赔偿保险金通知书，并说明理由。</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第十六条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">保险人自收到赔偿保险金的请求和有关证明、资料之日起六十日内，对其赔偿保险金的数额不能确定的，应当根据已有证明和资料可以确定的数额先予支付；保险人最终确定赔偿保险金的数额后，应当支付相应的差额。</span><span style="font-size:10px">&nbsp;</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<h3><span style="font-family:微软雅黑, sans-serif;font-weight:normal;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">投保人、被保险人义务</span><span style="font-family:微软雅黑, sans-serif;font-weight:normal"></span></h3><p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第十七条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">订立保险合同，保险人就保险标的或者被保险人的有关情况提出询问的，投保人应当如实告知。</span><span><br/>
</span><span style="font-size:10px">投保人故意或者因重大过失未履行前款规定的如实告知义务，足以影响保险人决定是否同意承保或者提高保险费率的，保险人有权解除保险合同。</span><span><br/>
</span><span style="font-size:10px">前款规定的合同解除权，自保险人知道有解除事由之日起，超过三十日不行使而消灭。自合同成立之日起超过二年的，保险人不得解除合同；发生保险事故的，保险人应当承担赔偿保险金的责任。</span><span><br/>
</span><span style="font-size:10px">投保人故意不履行如实告知义务的，保险人对于合同解除前发生的保险事故，不承担赔偿保险金的责任，并不退还保险费。</span><span><br/>
</span><span style="font-size:10px">投保人因重大过失未履行如实告知义务，对保险事故的发生有严重影响的，保险人对于合同解除前发生的保险事故，不承担赔偿保险金的责任，但应当退还保险费。</span><span><br/>
</span><span style="font-size:10px">保险人在合同订立时已经知道投保人未如实告知的情况的，保险人不得解除合同；发生保险事故的，保险人应当承担赔偿保险金的责任。</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第十八条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;&nbsp; </span><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">除另有约定外，投保人应在本合同成立时交清保险费。保险费未交清前，本合同不生效，保险人不承担保险责任。</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第十九条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">被保险人应当采取合理的预防措施，尽力避免或减少事故的发生，维护保险标的的安全。</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">保险人可以对被保险人遵守前款约定的情况进行检查，向投保人、被保险人提出消除不安全因素和隐患的书面建议，投保人、被保险人应该认真付诸实施。</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">投保人、被保险人未按照约定履行其对保险标的的安全应尽责任的，保险人有权要求增加保险费或者解除本合同。</span><span style="font-size:10px">&nbsp;</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第二十条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">保险标的转让的，被保险人或者受让人应当及时通知保险人。</span><span><br/>
</span><span style="font-size:10px">因保险标的转让导致危险程度显著增加的，保险人自收到前款规定的通知之日起三十日内，可以增加保险费或者解除本合同。</span><span><br/>
</span><span style="font-size:10px">被保险人、受让人未履行本条规定的通知义务的，因转让导致保险标的危险程度显著增加而发生的保险事故，保险人不承担赔偿保险金的责任。</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第二十一条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">在本合同有效期内，保险标的的危险程度显著增加的，被保险人应当及时通知保险人，保险人可以增加保险费或者解除本合同。</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">被保险人未履行前款约定的通知义务的，因保险标的的危险程度显著增加而发生的保险事故，保险人不承担赔偿保险金的责任。</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第二十二条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">知道保险事故发生后，被保险人应该：</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">（一）尽力采取必要、合理的措施，防止或减少损失，否则，对因此扩大的损失，保险人不承担赔偿责任；</span><span><br/>
</span><span style="font-size:10px">（二）及时通知保险人，并书面说明事故发生的原因、经过和损失情况；故意或者因重大过失未及时通知，致使保险事故的性质、原因、损失程度等难以确定的，保险人对无法确定的部分，不承担赔偿保险金的责任，但保险人通过其他途径已经及时知道或者应当及时知道保险事故发生的除外；</span><span><br/>
</span><span style="font-size:10px">（三）保护事故现场，允许并且协助保险人进行事故调查；对于拒绝或者妨碍保险人进行事故调查导致无法确定事故原因或核实损失情况的，保险人对无法确定或核实的部分不承担赔偿责任。</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第二十三条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">被保险人收到向其提出赔偿要求的受害第三者或其他索赔权利人（以下统称为“索赔人”）的损害赔偿请求时，应立即通知保险人。未经保险人书面同意，被保险人对索赔人及其代理人作出的任何承诺、拒绝、出价、约定、付款或赔偿，保险人不受其约束。对于被保险人自行承诺或支付的赔偿金额，保险人有权重新核定，不属于本保险责任范围或超出应赔偿限额的，保险人不承担赔偿责任。在处理索赔过程中，保险人有权自行处理由其承担最终赔偿责任的任何索赔案件，被保险人有义务向保险人提供其所能提供的资料和协助。</span><span style="font-size:10px">&nbsp;</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第二十四条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">被保险人获悉可能发生诉讼、仲裁时，应立即以书面形式通知保险人；接到法院传票或其他法律文书后，应将其副本及时送交保险人。保险人有权以被保险人的名义处理有关诉讼或仲裁事宜，被保险人应提供有关文件，并给予必要的协助。</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">对因未及时提供上述通知或必要协助导致扩大的损失，保险人不承担赔偿责任。</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第二十五条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">被保险人请求赔偿时，应向保险人提供保险单、事故情况说明及相关证明、损失清单、必要的发票和单据，以及投保人或被保险人所能提供的与确认保险事故的性质、原因、损失程度等有关的其他证明和资料。</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p align="left"><span style="font-family:微软雅黑, sans-serif;font-size:10px">被保险人未履行前款约定的索赔材料提供义务，导致保险人无法核实损失情况的，保险人对无法核实的部分不承担赔偿责任。</span><span></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第二十六条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">保险事故发生时，被保险人对保险标的不具有保险利益的，不得向保险人请求赔偿保险金。</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第二十七条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">保险标的因保险事故而受损，被保险人应以修复为原则尽量修复，保险人负责赔偿相关修理费用。</span><span><br/>
</span><span style="font-size:10px">除为防止或减少保险标的损失而进行的紧急修理，被保险人应在修理或重建前会同保险人对受损保险标的进行检验，确定修理或重建的项目、方式和费用，否则，保险人有权重新核定。</span><span><br/>
</span><span style="font-size:10px">保险人仅负责赔偿将受损保险标的恢复到受损前状态的修理或重建费用，对于受损保险标的在修复或重建过程中发生的任何变更、性能增加或改进而产生的额外费用，保险人不负责赔偿。</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第二十八条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">发生家庭财产保险责任范围内的损失，保险人按以下方式计算赔偿：</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第二十九条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">保险赔偿结案后，保险人不再负责赔偿任何新增加的与该次保险事故相关的损失、费用或赔偿责任。</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">当一次保险事故涉及多名第三者时，如果保险人和被保险人双方已经确认了其中部分第三者的赔偿金额，保险人可根据被保险人的申请予以先行赔付。先行赔付后，保险人不再负责赔偿与这些第三者相关的任何新增加的赔偿金。</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第三十条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">被保险人向保险人请求赔偿保险金的诉讼时效期间为二年，自其知道或者应当知道保险事故发生之日起计算。</span><span style="font-size:10px">&nbsp;</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<h3><span style="font-family:微软雅黑, sans-serif;font-weight:normal;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">争议处理和法律适用</span><span style="font-family:微软雅黑, sans-serif;font-weight:normal"></span></h3><p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第三十一条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">因履行本合同发生的争议，由当事人协商解决。协商不成的，提交保险单载明的仲裁机构仲裁；保险单未载明仲裁机构且争议发生后未达成仲裁协议的，依法向中华人民共和国人民法院起诉。</span><span style="font-size:10px">&nbsp;</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第三十二条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">本合同的争议处理适用中华人民共和国法律。</span><span style="font-size:10px">&nbsp;</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<h3><span style="font-family:微软雅黑, sans-serif;font-weight:normal;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">其他事项</span><span style="font-family:微软雅黑, sans-serif;font-weight:normal"></span></h3><p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第三十三条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">本合同成立后，投保人可要求解除本合同。投保人要求解除本合同的，应当向保险人提出书面申请，本合同自保险人收到书面申请时终止。</span><span style="font-size:10px">&nbsp;</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第三十四条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">本合同成立后，保险人根据保险法规定或者本合同约定要求解除本合同的，除保险法另有规定或本合同另有约定外，本合同自解除通知送达投保人最后所留通讯地址时终止。</span><span style="font-size:10px">&nbsp;</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第三十五条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">在保险单中载明的保险责任起始日前，投保人要求解除本合同的，除本合同另有约定外，投保人应当按照保险费</span><span style="font-size:10px">5%</span><span style="font-size:10px">的比例向保险人支付手续费，保险人退还已收取的保险费。</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">在保险单中载明的保险责任起始日后解除本合同的，除本合同另有约定外，保险人应向投保人退还未满期保险费。</span><span><br/>
</span><span style="font-size:10px">如果解除时，本合同项下仍有尚未赔偿结案的保险事故，保险人可在赔偿结案后再向投保人退还未满期保险费。</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<h3><span style="font-family:微软雅黑, sans-serif;font-weight:normal;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">释义</span><span style="font-family:微软雅黑, sans-serif;font-weight:normal"></span></h3><p><strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">第三十六条</span></strong><span style="font-family:微软雅黑, sans-serif;font-size:10px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial">&nbsp;</span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial"><span style="font-size:10px">除另有约定外，本合同中的下列词语具有如下含义：</span><span style="font-size:10px">&nbsp;<br/>
</span><span style="font-size:10px">保险人：是指中国太平洋财产保险股份有限公司。</span><span><br/>
</span><span style="font-size:10px">人身伤害：是指死亡、肢体残疾、组织器官功能障碍及其他影响人身健康的损伤。</span><span><br/>
</span><span style="font-size:10px">合法饲养：是指被保险人的养犬手续符合全国及地方性犬类管理法律法规的相关规定，所养的犬具有有效的养犬登记证和动物健康免疫证，并通过年检审查。</span><span><br/>
</span><span style="font-size:10px">第三者：是指被保险人及其家庭成员以外的自然人。</span><span><br/>
</span><span style="font-size:10px">被保险人家庭成员：是指被保险人的直系血亲、配偶、养父母或有扶养关系的继父母、岳父母或公婆、养子女或有扶养关系的继子女、兄弟姐妹、同父异母或同母异父的兄弟姐妹、养兄弟姐妹或有扶养关系的继兄弟姐妹。</span><span><br/>
</span><span style="font-size:10px">累计赔偿金额：是指在实际保险期间内，由保险人负责赔偿的保险赔偿金之和，但不包括保险人负责赔偿的法律费用。</span><span><br/>
</span><span style="font-size:10px">实际保险期间：是指自保险单载明的保险责任起始日零时起至本合同终止日二十四时止。</span><span><br/>
</span><span style="font-size:10px">剩余保险期间：是指自本合同终止日次日零时起至保险单载明的保险责任终止日二十四时止。</span><span><br/>
</span><span style="font-size:10px">未满期保险费：是指保险人应退还的剩余保险期间的保险费，未满期保险费按照以下公式计算：</span><span><br/>
</span><span style="font-size:10px">未满期保险费</span><span style="font-size:10px">=</span><span style="font-size:10px">保险费×（剩余保险期间天数</span><span style="font-size:10px">/</span><span style="font-size:10px">保险期间天数）×（累计赔偿限额－累计赔偿金额）</span><span style="font-size:10px">/</span><span style="font-size:10px">累计赔偿限额</span><span><br/>
</span><span style="font-size:10px">其中，累计赔偿金额是指在实际保险期间内，保险人已支付的保险赔偿金和已发生保险事故但还未支付的保险赔偿金之和，但不包括保险人负责赔偿的法律费用。</span></span><span style="font-size:10.5pt;font-family:微软雅黑, sans-serif"></span></p>
<p><span style="font-size:10px">&nbsp;</span></p>
              </main>
			  </div>
			</div>
		</div>
	</body>
</html>
