<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>个人账户资金损失险-条款</title>
<%@include file="../../common/head.jsp"%>
</head>
<body onload="loaded();">
		<div id="baoqiandai_content" style="width: 100%;">
			<!-- <div data-role="header" data-position="fixed" class="zll_header" data-tap-toggle="false">
				onclick="$.mobile.changePage('../../index.html', 'slideup');"
			    <a data-ajax="false" href="javascript:history.go(-1);" class="ui-btn ui-corner-all ui-btn-icon-notext ui-icon-back">返回</a>
			    <h2>个人账户资金损失险</h2>
			</div> -->
            <header>
                <div class="header-left" onclick="history.go(-1);">
                  <div class="header-btn-area">
                      <!-- <i class="iconfont icon-fanhuijiantou"></i> --> 
                      <%-- <img src="${staticPath }/img/icon/left.png" width="15px" alt="" height="15px"/> --%>
                      <!-- <span class="left-btn"></span> -->
                      <span class="icon_img back"></span>
                  </div>
                </div>
                <div class="header-tit"><h2>个人账户资金安全险</h2></div>
                <div class="header-right">
                  
                </div>
           </header>
			<!--内容页-->
			<div id="wrapper" >
          <div id="scroller">
              <main class="ui-content insurance_detail">
			   <div>
<div style="text-align:center"><span style="font-size:10px">&nbsp;</span><b style="text-align:center"><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">总则</span></b></div>
</div>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第一条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">本保险合同由保险条款、投保单、保险单、保险凭证以及批单组成。凡涉及本保险合同的约定，均应采用书面形式。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第二条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">本保险合同所指的被保险人，为存折、银行卡、网银账户、以及经中国人民银行批准的支付机构账户（以下简称第三方支付账户）的所有人或他人信用卡附属卡的合法持有人。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="center" style="text-align:center"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">保险标的</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第三条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">本保险合同的保险标的为“被保险人的个人账户”，包括：</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（一）</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">被保险人名下的存折；</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（二）</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">银行卡，包括：</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">1.</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">被保险人名下的借记卡；</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">2.</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">被保险人名下的信用卡主卡及与其关联的附属卡；</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">3.</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">以被保险人为持卡人的信用卡附属卡；</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（三）</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">被保险人名下的网银账户；</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（四）</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">被保险人名下的第三方支付账户（包括但不限于支付宝、财付通、易付宝、微信钱包）。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（五）</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">其他经保险人同意的被保险人的个人账户也可以成为本保险合同的保险标的。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">投保人就以上各项保险标的可以选择投保，并以保险单载明为准。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="center" style="text-align:center"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">保险责任</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第四条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">在保险期间内，由于下列原因造成保险标的的损失，保险人按照本保险合同的约定负责赔偿：</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（一）</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">被保险人的个人账户因他人盗刷、盗用、复制而导致的资金损失；</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（二）</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">被保险人的个人账户被他人在银行柜面及</span><span style="font-family:'color:#333333';font-size:10px">ATM</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">机器上盗取或转账导致的资金损失；</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（三）</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">被保险人在被歹徒胁迫的状态下，将其个人账户交给他人使用，或将个人账户的账号及密码透露给他人导致的资金损失；</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（四）</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">被保险人名下的信用卡主卡所关联的附属卡的持卡人在被歹徒胁迫的状态下，将附属卡交给他人使用，或透露该附属卡账号及密码给他人导致的资金损失。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第五条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">保险事故发生后，被保险人为防止或减少保险标的的损失所支付的必要的、合理的费用，保险人按照本保险合同的约定也负责赔偿。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="center" style="text-align:center"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">责任免除</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第六条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">下列原因造成的损失、费用，保险人不负责赔偿：</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（一）</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">投保人、被保险人及其代表的故意、重大过失或犯罪行为；</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（二）</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">行政行为或司法行为；</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（三）</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">被保险人的个人账户在借给他人使用期间或被他人诈骗所导致的资金损失；</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（四）</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">在没有被胁迫的情况下，被保险人或被保险人的信用卡主卡所关联的附属卡持有人主动向他人划转资金或付款的行为，以及主动向他人透露个人账户号及密码导致的资金损失；</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（五）</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">被保险人的个人账户在挂失或冻结前</span></b><b><span style="font-family:'color:#333333';font-size:10px">72</span></b><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">小时以外的损失；</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（六）</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">被保险人或被保险人的信用卡主卡所关联的附属卡持有人未遵循银行账户及第三方支付账户使用规范，导致的资金损失。</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第七条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">下列损失、费用，保险人也不负责赔偿：</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（一）</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">被保险人的间接损失；</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（二）</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">本保险合同中载明的免赔额以及按本保险合同中载明的免赔率计算的免赔额，两者以高者为准。</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="center" style="text-align:center"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">保险金额与免赔额（率）</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第八条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">保险金额由投保人和保险人协商确定，并在保险单中载明。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">投保人和保险人也可以协商确定每次事故赔偿限额，并在保险单中载明。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第九条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">免赔额（率）由投保人与保险人在订立保险合同时协商确定，并在保险单中载明。</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="center" style="text-align:center"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">保险期间</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第十条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">除另有约定外，保险期间为一年，以保险单载明的起讫时间为准。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="center" style="text-align:center"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">保险人义务</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第十一条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">本保险合同成立后，保险人应当及时向投保人签发保险单或其他保险凭证。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第十二条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">保险事故发生后，投保人、被保险人提供的有关索赔的证明和资料不完整的，保险人应当及时一次性通知投保人、被保险人补充提供。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第十三条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">保险人收到被保险人的赔偿请求后，应当及时就是否属于保险责任作出核定，并将核定结果通知被保险人。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="center" style="text-align:center"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">投保人、被保险人义务</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第十四条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">投保人应履行如实告知义务，如实回答保险人就保险标的或被保险人的有关情况提出的询问，并如实填写投保单。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第十五条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">除本保险合同另有约定外，投保人应在保险合同成立时一次交清保险费。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第十六条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">保险事故发生时，被保险人应当尽力采取必要的措施，防止或者减少损失。投保人、被保险人知道保险事故发生后，应当及时通知保险人。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第十七条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">发生保险责任范围内的损失，应由有关责任方负责赔偿的，被保险人应行使或者保留向该责任方请求赔偿的权利。</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;<br/>
</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">在保险人向有关责任方行使代位请求赔偿权利时，被保险人应当向保险人提供必要的文件和其所知道的有关情况。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第十八条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">被保险人向保险人请求赔偿时，应提交以下单证：</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（一）</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">保险单正本或保险单号；</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（二）</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">被保险人的身份证复印件；</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（三）</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">与个人账户被盗刷、盗用、盗取、转账等相关的交易记录；</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（四）</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">有关损失资金的流向记录，比如涉及转账，需提供收款方姓名及账号等信息；</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（五）</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">个人账户挂失或冻结时间证明；</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（六）</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">公安机关证明；</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><span style="font-family:'color:#333333';font-size:10px">&nbsp;&nbsp;&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（七）</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">投保人、被保险人所能提供的其他与确认保险事故的性质、原因、损失程度等有关的证明和资料。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="center" style="text-align:center"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">赔偿处理</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第十九条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">保险标的发生保险责任范围内的损失，保险人以支付保险金的方式赔偿。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第二十条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">保险标的发生保险责任范围内的损失时，对于每次事故造成的损失，保险人按照其实际损失扣除本保险合同约定的免赔额或按本保险合同载明的免赔率计算的免赔额后，在每次事故赔偿限额范围内计算赔偿。累计赔偿金额达到保险金额后，保险合同自动终止。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="center" style="text-align:center"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">争议处理和法律适用</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第二十一条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">合同争议解决方式由当事人在合同约定从下列两种方式中选择一种：</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span></p>
<p align="left"><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（一）因履行本合同发生的争议，由当事人协商解决，协商不成的，提交保险单载明的仲裁委员会仲裁；</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span></p>
<p align="left"><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">（二）因履行本合同发生的争议，由当事人协商解决，协商不成的，依法向人民法院起诉。</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第二十二条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">与本保险合同有关的以及履行本保险合同产生的一切争议处理适用中华人民共和国法律（不包括港澳台地区法律）。</span><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span></p>
<p align="center" style="text-align:center"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">其他事项</span></b><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第二十三条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">被保险人个人账户中的资金如涉及外币，均以发生保险责任事故当日中国人民银行公布的相应外汇基准价折算人民币。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第二十四条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">保险责任开始前，投保人要求解除保险合同的，应当按照保险合同约定向保险人支付退保手续费，保险人应当退还剩余部分保险费。保险责任开始后，投保人要求解除保险合同的，自通知保险人之日起，保险合同解除，保险人按照保险责任开始之日起至合同解除之日止期间与保险期间的日比例计收保险费，并退还剩余部分保险费。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p align="left"><b><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">第二十五条</span></b><span style="font-family:'color:#333333';font-size:10px">&nbsp;</span><span style="font-family:宋体;color:rgb(51, 51, 51);font-size:10px">本保险合同约定与《中华人民共和国保险法》等法律规定相悖之处，以法律规定为准。本保险合同未尽事宜，以法律规定为准。</span><span style="font-size:9.0pt;font-family:&quot;color:#333333"></span></p>
<p><span style="font-size:10px">&nbsp;</span></p>
         	</main>
        	</div>
          </div>
          
		</div>
	</body>
</html>
